linters:
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - varnamelen
  presets:
    - bugs
    - unused
    - complexity
    - error
    - format
    - import
    - module
    - performance
    - style
    - test
linters-settings:
  stylecheck:
    checks: ["all", "-ST1005"]
